id: A9999A841
title: Short Torma Offering to Kurukullā
type: translation
pechas:
- I8B1492C4
- I98FCA837
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:08:56.701292
  last_modified_at: 2023-01-04 13:08:56.701312
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8B1492C4/8668: '8668'
  I98FCA837/9F78: '8668'
